<!DOCTYPE html>
<html>
<head>
    <title>E-Way Bill</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 0;
            padding: 0;
            color: #000;
        }

        .container {
            border: 2px solid #000; /* Outer black border */
            padding: 20px;
            margin: 10px;
        }

        .title {
            text-align: center;
            font-size: 16px;
            font-weight: bold;
            padding-bottom: 6px;
            border-bottom: 1px solid #000;
        }

        .qr {
            text-align: center;
            margin: 12px 0;
        }

        .qr img {
            width: 100px;
            height: 100px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 12px;
        }

        th, td {
            padding: 6px 8px;
            border: 1px solid #ccc; /* Light gray for all internal table borders */
            vertical-align: top;
        }

        th {
            width: 30%;
            background-color: #f3f3f3;
            text-align: left;
        }

        .section-title {
            background-color: #ddd;
            font-weight: bold;
            text-align: left;
            padding: 6px 8px;
            border: 1px solid #ccc;
            margin-bottom: 4px;
        }

        .footer {
            font-size: 10px;
            color: #555;
            margin-top: 10px;
            border-top: 1px solid #ccc;
            padding-top: 6px;
        }
    </style>
</head>
<body>

<div class="container">

    <div class="title">E-WAY BILL</div>

    <div class="qr">
    <img style="width: 180px; height:180px;"
         src="{{ $qrLink && filter_var($qrLink, FILTER_VALIDATE_URL) ? $qrLink : 'https://mazingbusiness.com/public/uploads/no_qr_link.png' }}"
         alt="QR Code">
</div>

    <table>
        <tr><th>E-Way Bill No.</th><td>{{ $eway['ewaybill_no'] }}</td></tr>
        <tr><th>E-Way Bill Date</th><td>{{ $eway['ewaybill_date'] }}</td></tr>
        <tr><th>Status</th><td>{{ $eway['status'] }}</td></tr>
        <tr><th>Valid From</th><td>{{ $eway['valid_from'] }}</td></tr>
        <tr><th>IRN</th><td>{{ $eway['irn'] }}</td></tr>
    </table>

    <div class="section-title">Part - A</div>

    <table>
        <tr><th>GSTIN of Supplier</th><td>{{ $eway['supplier_gstin'] }}</td></tr>
        <tr><th>Place of Dispatch</th><td>{{ $eway['place_of_dispatch'] }}</td></tr>
        <tr><th>GSTIN of Recipient</th><td>{{ $eway['recipient_gstin'] }}</td></tr>
        <tr><th>Place of Delivery</th><td>{{ $eway['place_of_delivery'] }}</td></tr>
        <tr><th>Document No.</th><td>{{ $eway['doc_no'] }}</td></tr>
        <tr><th>Document Date</th><td>{{ $eway['doc_date'] }}</td></tr>
        <tr><th>Transaction Type</th><td>{{ $eway['transaction_type'] }}</td></tr>
        <tr><th>Value of Goods</th><td>{{ $eway['goods_value'] }}</td></tr>
        <tr>
            <th>HSN Code</th>
            <td>
                @php
                    $codes = array_filter(explode(',', $eway['hsn_code']));
                    $first = $codes[0] ?? '-';
                    $count = count($codes) - 1;
                @endphp
                {{ $first }}@if($count > 0) (+{{ $count }})@endif
            </td>
        </tr>

        <tr><th>Reason for Transportation</th><td>{{ $eway['reason'] }}</td></tr>
        <tr><th>Transporter</th><td>{{ $eway['transporter'] }}</td></tr>
    </table>

    <div class="footer">
        Note: This PDF is generated by Zoho Books and reflects the E-Way Bill data issued.
    </div>

</div>

</body>
</html>
