<!DOCTYPE html>
<html>
<head>
    <title>Manager Report - {{ $manager_name }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ccc;
            padding: 10px;
            text-align: center;
            font-size: 14px;
        }
        th {
            background-color: #f1f1f1;
            font-weight: bold;
        }
        h3 {
            text-align: center;
            margin-top: 20px;
            font-size: 20px;
            color: #174e84;
        }
        .summary-table {
            margin-top: 20px;
        }
        .total-row strong {
            font-size: 16px;
        }
        .header-image {
            width: 100%;
            height: auto;
        }
        .company-details {
            font-size: 14px;
            text-align: left;
            margin-top: 20px;
        }
        .company-details strong {
            color: #174e84;
        }
        .city-header-row td {
            background-color: #f9f9f9;
            font-weight: bold;
            text-align: left;
            padding-left: 10px;
            font-size: 16px;
        }
        .footer {
            background-color: #174e84;
            color: #fff;
            text-align: center;
            font-weight: bold;
            padding: 10px 0;
            margin-top: 20px;
        }
    </style>
</head>
<body>

<!-- Report Header -->
<table width="100%" cellpadding="0" cellspacing="0" style="border-collapse: separate; border-spacing: 0;">
    <tr>
        <td style="text-align: right; border: none; padding: 0;">
            <img src="https://mazingbusiness.com/public/assets/img/pdfHeader.png" class="header-image" alt="Header Image" />
        </td>
    </tr>
</table>

<!-- Company Details -->
<table class="company-details" width="100%" cellpadding="10" cellspacing="0" style="border: none;">
    <tr>
        <td width="50%" style="vertical-align: top;">
            <strong>ACE TOOLS PRIVATE LIMITED</strong><br>
            Plot No 220/219 & 220 Kh No 58/2,<br>
            Rithala Road, Rithala,<br>
            New Delhi - 110085<br>
            GSTIN: 07AACCA0111K1ZN
        </td>
    </tr>
</table>

<!-- Manager Report Header -->
<h3>Statement Report for {{ $manager_name }}</h3>

<!-- Add Date Below the Statement Heading -->
<p style="text-align: center; font-size: 14px; margin-bottom: 30px;">
    <strong>Date:</strong> {{ now()->format('d M Y') }} <!-- Display current date below the heading -->
</p>

<!-- Generated Data Below the Date -->
<!-- Summary Table -->
<table class="summary-table" cellspacing="0" cellpadding="10">
    <tr>
        <td style="text-align: center;">
            <strong>Total Due Amount</strong><br>
            ₹{{ number_format($totalDueAmount, 2) }}
        </td>
        <td style="text-align: center;">
            <strong>Total Overdue Amount</strong><br>
            ₹{{ number_format($totalOverdueAmount, 2) }}
        </td>
    </tr>
</table>

<!-- Detailed Table with Customer Data -->
<table cellspacing="0" cellpadding="10" style="margin-top: 25px; border-collapse: collapse; width: 100%;">
    <thead>
        <tr>
            <th>#</th>
            <th>Customer Name</th>
            <th>City</th>
            <th>Phone</th>
            <th>Due Amount</th>
            <th>Overdue Amount</th>
            <th>Overdays</th>
        </tr>
    </thead>
    <tbody>
        @php $serial = 1; @endphp
        @foreach($processedData as $data)
            <tr>
                <td>{{ $serial++ }}</td>
                <td>{{ $data['customer']['company_name'] }}</td> <!-- Accessed as array -->
                <td>{{ $data['city'] }}</td>
                <td>{{ $data['phone'] }}</td>
                <td>₹{{ number_format($data['address']->due_amount, 2) }}</td>
                <td>₹{{ number_format($data['address']->overdue_amount, 2) }}</td>
                <td>({{ getFirstOverdueDays(encrypt($data['address']->acc_code))->getData()->overdue_days ?? 'No overdue days' }})</td>
            </tr>
        @endforeach
    </tbody>
</table>

<!-- Footer -->
<div class="footer">
    Generated by Mazing Business
</div>

</body>
</html>
